version: 1
disable_existing_loggers: False

formatters:
    console:
        () : main.CustomFormatter # Actually, we're overriding this when importing the file.

    file:
        format: "[%(asctime)s] [%(levelname)s] - %(message)s"
        datefmt: "%Y-%m-%d %H:%M"
    discord:
        format: "[%(asctime)s] %(message)s"
        datefmt: "%Y-%m-%d %H:%M"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: console
        stream: ext://sys.stdout

    file:
        class: logging.FileHandler
        level: INFO
        formatter: file
        filename: logs/applog.txt
        mode: w
        encoding: utf8

    discord:
        class: discord_handler.DiscordWebhookHandler
        level: INFO
        formatter: discord
        webhook_url: null  # Will be set programmatically

loggers:
    development:
        level: DEBUG
        handlers: [console, file, discord] # Keep this order.
        propagate: no

    production:
        level: INFO
        handlers: [file, discord]
        propagate: no
